spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=postgres

api.security.token.secret =${JWT_SECRET:my-secret-key}
logging.level.org.springframework.security=DEBUG

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate=DEBUG